[metadata]
name = arbdmodel
version = file: arbdmodel/RELEASE-VERSION
description = ARBD simulation interface
long_description = file: README.md
long_description_content_type = text/markdown

author = Christopher Maffeo
author_email = cmaffeo2@illinois.edu
url = https://gitlab.engr.illinois.edu/tbgl/tools/arbdmodel,
project_urls =
    gitlab repository = https://gitlab.engr.illinois.edu/tbgl/tools/arbdmodel,

license = University of Illinois Open Source License
license_file = LICENSE
platforms = unix, linux, osx, cygwin, win32
classifiers =
    Programming Language :: Python :: 3,
    License :: UIUC Open source License
    Operating System :: OS Independent

[options]
include_package_data = True
packages = find:
install_requires =
    numpy>=1.14
    scipy>=1.1
    mdanalysis>=2.0.0
    appdirs>=1.4
    pandas>=1.0.0
python_requires = >=3.5
zip_safe = no
